import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useRouter } from "next/router";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const router = useRouter();

  const navigateToCreateJoke = () => {
    router.push("/create-joke");
  };

  const navigateToReadJoke = () => {
    router.push("/read-joke");
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>
          <div className={styles.buttons}>
            <button
              className={styles.button}
              onClick={() => {
                navigateToReadJoke();
              }}
            >
              Read Joke
            </button>
            <button
              className={styles.button}
              onClick={() => {
                navigateToCreateJoke();
              }}
            >
              Create Joke
            </button>
          </div>
        </div>
      </main>
    </>
  );
}
